<a href="https://www.kaggle.com/code/pes1ug22am164/image-part?scriptVersionId=171996997" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# uncomment on google colab, comment on kaggle.

In [1]:
# !mkdir ~/.kaggle
# from google.colab import files
# files.upload()
# !cp kaggle.json ~/.kaggle/
# !chmod 600 ~/.kaggle/kaggle.json
# !kaggle datasets download -d shusrith/betterer-preproc

In [2]:
# !unzip /content/betterer-preproc.zip

In [3]:
# !kaggle datasets download -d tourist55/alzheimers-dataset-4-class-of-images

In [4]:
# !unzip /content/alzheimers-dataset-4-class-of-images.zip

# PRE PROCESS
.JPG TO .NPY

In [5]:
import os
import cv2
import numpy as np

def jpg_to_npy_in_folders(input_folder, output_folder):
    os.makedirs(output_folder, exist_ok=True)
    for i, item in enumerate(os.listdir(input_folder)):
        item_path = os.path.join(input_folder, item)
        if os.path.isdir(item_path):
            jpg_to_npy_in_folders(item_path, output_folder)
        elif os.path.isfile(item_path) and item.endswith(".jpg"):
            img = cv2.imread(item_path)
            img_array = np.array(img)
            output_file_path = os.path.join(output_folder, os.path.splitext(item)[0] + '.npy')
            np.save(output_file_path, img_array)

input_folder_path = "/kaggle/input/alzheimers-dataset-4-class-of-images/Alzheimer_s Dataset/train"
output_folder_path = "/kaggle/working/train"

jpg_to_npy_in_folders(input_folder_path, output_folder_path)



In [6]:
import os
import cv2
import numpy as np

def jpg_to_npy_in_folders(input_folder, output_folder):
    os.makedirs(output_folder, exist_ok=True)
    for i, item in enumerate(os.listdir(input_folder)):
        item_path = os.path.join(input_folder, item)
        if os.path.isdir(item_path):
            jpg_to_npy_in_folders(item_path, output_folder)
        elif os.path.isfile(item_path) and item.endswith(".jpg"):
            img = cv2.imread(item_path)
            img_array = np.array(img)
            folder = input_folder.split("/")[-1]
            output_file_path = os.path.join(output_folder, f"{folder}{i}.npy")
            np.save(output_file_path, img_array)

# input_folder_path = "/kaggle/input/alzheimers-dataset-4-class-of-images/Alzheimer_s Dataset/train"
# output_folder_path = "/kaggle/working/train"

# jpg_to_npy_in_folders(input_folder_path, output_folder_path)
jpg_to_npy_in_folders("/kaggle/input/alzheimers-dataset-4-class-of-images/Alzheimer_s Dataset/test", "/kaggle/working/test")



In [7]:
import os
import numpy as np
directory = '/kaggle/working/train'

files = [file for file in os.listdir(directory) if file.endswith('.npy')]
len(files)


5121

In [8]:
mildDem = [i for i in files if i.startswith("mildDem")]
moderateDem = [i for i in files if "moderateDem" in i]
nonDem = [i for i in files if "nonDem" in i]
veryMild = [i for i in files if "verymildDem" in i]
print(len(mildDem), len(moderateDem), len(nonDem), len(veryMild))

717 52 2560 1792


In [9]:
import imgaug.augmenters as iaa

# Define the augmenter
augmenter = iaa.Sequential([
    iaa.Affine(rotate=(-10, 10)),  # Rotate the image by -10 to 10 degrees
    iaa.GaussianBlur(sigma=(0.0, 1.0)),  # Apply Gaussian blur with a sigma ranging from 0.0 to 1.0
    iaa.AdditiveGaussianNoise(scale=(0, 0.05*255)),  # Add Gaussian noise with a scale of 0 to 0.05 times 255
    iaa.Multiply((0.9, 1.1)),
    iaa.LinearContrast((0.9, 1.1)),
])

augmented_images = []

for path in moderateDem:
    path = os.path.join("/kaggle/working/train", path)
    image = np.load(path)

    for _ in range(35):
        augmented_image = augmenter.augment_image(image)
        augmented_images.append(augmented_image)
augmented_images = np.array(augmented_images)

In [10]:
len(augmented_images)

1820

In [11]:
import cv2
import os


output_directory = "/kaggle/working/train"

os.makedirs(output_directory, exist_ok=True)

for i, image in enumerate(augmented_images):
    output_path = os.path.join(output_directory, f"moderateDem{i+53}.npy")
    np.save(output_path, image)


print("Augmented images saved successfully.")


Augmented images saved successfully.


In [12]:
augmented_images = []

for path in mildDem:
    path = os.path.join("/kaggle/working/train", path)
    image = np.load(path)

    for _ in range(3):
        augmented_image = augmenter.augment_image(image)
        augmented_images.append(augmented_image)
augmented_images = np.array(augmented_images)

In [13]:
len(augmented_images)

2151

In [14]:
output_directory = "/kaggle/working/train"

os.makedirs(output_directory, exist_ok=True)

for i, image in enumerate(augmented_images):
    output_path = os.path.join(output_directory, f"mildDem{i+718}.npy")
    np.save(output_path, image)


print("Augmented images saved successfully.")

Augmented images saved successfully.


In [15]:
import os
import numpy as np
directory = '/kaggle/working/train'

files = [file for file in os.listdir(directory) if file.endswith('.npy')]
len(files)

9092

In [16]:
mildDem = [i for i in files if i.startswith("mildDem")]
moderateDem = [i for i in files if "moderateDem" in i]
nonDem = [i for i in files if "nonDem" in i]
veryMild = [i for i in files if "verymildDem" in i]
print(len(mildDem), len(moderateDem), len(nonDem), len(veryMild))

2868 1872 2560 1792


In [17]:
import pandas as pd
l = [[mildDem, 0], [moderateDem, 1], [nonDem, 2], [veryMild, 3]]
x = []
for i in l:
    for j in i[0]:
        path = os.path.join("/kaggle/working/train", j)
        x.append([i[1], path])

df = pd.DataFrame(x, columns=["Class", "Path"])
x = df["Class"].value_counts()
x

Class
0    2868
2    2560
1    1872
3    1792
Name: count, dtype: int64

In [18]:
images = []
for i in df["Path"]:
    images.append(np.load(i))
images = np.array(images)

In [19]:
from sklearn.model_selection import train_test_split
labels = np.array(df["Class"])
train_images, test_images, train_labels, test_labels = train_test_split(images, labels, test_size=0.2, random_state=42)


In [20]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
train_labels_encoded = label_encoder.fit_transform(train_labels)
test_labels_encoded = label_encoder.transform(test_labels)

# Verify the encoded labels
print(train_labels_encoded)
print(test_labels_encoded)

[3 2 2 ... 2 0 2]
[2 0 0 ... 3 1 0]


In [21]:
print(train_images.shape, test_images.shape, train_labels_encoded.shape, test_labels_encoded.shape)

(7273, 208, 176, 3) (1819, 208, 176, 3) (7273,) (1819,)


In [22]:
print(test_labels)
test_labels_encoded

[2 0 0 ... 3 1 0]


array([2, 0, 0, ..., 3, 1, 0])

In [23]:
print(x.index, x.values, x.array)

Index([0, 2, 1, 3], dtype='int64', name='Class') [2868 2560 1872 1792] <NumpyExtensionArray>
[2868, 2560, 1872, 1792]
Length: 4, dtype: int64


In [24]:
s = x / len(files)
class_weights = {i:j for i, j in zip(s.index, s.values)}

class_weights
# Optional normalization (weights sum to 1)
# total_weight = sum(class_weights.values())
# class_weights = {class_label: weight / total_weight for class_label, weight in class_weights.items()}


{0: 0.31544214694236694,
 2: 0.28156621205455346,
 1: 0.20589529256489222,
 3: 0.1970963484381874}

In [25]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, Input
from keras.callbacks import EarlyStopping, LearningRateScheduler
from keras.utils import to_categorical
from sklearn.utils.class_weight import compute_sample_weight
from sklearn.model_selection import train_test_split
import numpy as np

# Assuming train_images and test_images are your input image data
input_shape = train_images[0].shape

train_labels_encoded = to_categorical(train_labels, num_classes=4)
test_labels_encoded = to_categorical(test_labels, num_classes=4)

sample_weights = compute_sample_weight(class_weight='balanced', y=np.argmax(train_labels_encoded, axis=1))

model = Sequential()
model.add(Input(shape=input_shape))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(256, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(4, activation='softmax'))


2024-04-16 17:21:19.383018: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-16 17:21:19.383159: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-16 17:21:19.492066: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


In [26]:
from keras.optimizers import Adam
def lr_schedule(epoch, learning_rate):
    if epoch < 20:
        return learning_rate
    else:
        if epoch % 2 == 0:
          return learning_rate * 0.95
        else:
          return learning_rate

lr_scheduler = LearningRateScheduler(lr_schedule, verbose=1)

initial_learning_rate = 0.001
optimizer = Adam(learning_rate=initial_learning_rate)

In [27]:
import math
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

history = model.fit(train_images, train_labels_encoded,
                    steps_per_epoch = int(len(train_images) / 32),
                    epochs=50,
                    validation_data=(test_images, test_labels_encoded),
                    sample_weight=sample_weights,
                    callbacks=[lr_scheduler])


Epoch 1: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 1/50
  1/227 ━━━━━━━━━━━━━━━━━━━━ 1:11:15 19s/step - accuracy: 0.2424 - loss: 34.0162

I0000 00:00:1713288110.767854      77 device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
W0000 00:00:1713288110.789794      77 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


221/227 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.4513 - loss: 68.2142

W0000 00:00:1713288140.362241      75 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update
/opt/conda/lib/python3.10/contextlib.py:153: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self.gen.throw(typ, value, traceback)
W0000 00:00:1713288146.479534      75 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


227/227 ━━━━━━━━━━━━━━━━━━━━ 60s 182ms/step - accuracy: 0.4525 - loss: 66.8096 - val_accuracy: 0.5003 - val_loss: 0.9895 - learning_rate: 0.0010

Epoch 2: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 2/50


W0000 00:00:1713288152.127078      77 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


227/227 ━━━━━━━━━━━━━━━━━━━━ 43s 85ms/step - accuracy: 0.5042 - loss: 0.9153 - val_accuracy: 0.4926 - val_loss: 0.8926 - learning_rate: 0.0010

Epoch 3: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 3/50
227/227 ━━━━━━━━━━━━━━━━━━━━ 20s 86ms/step - accuracy: 0.4955 - loss: 0.8647 - val_accuracy: 0.4651 - val_loss: 0.8720 - learning_rate: 0.0010

Epoch 4: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 4/50
227/227 ━━━━━━━━━━━━━━━━━━━━ 20s 87ms/step - accuracy: 0.5021 - loss: 0.8339 - val_accuracy: 0.5382 - val_loss: 0.8099 - learning_rate: 0.0010

Epoch 5: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 5/50
227/227 ━━━━━━━━━━━━━━━━━━━━ 20s 88ms/step - accuracy: 0.5514 - loss: 0.8112 - val_accuracy: 0.5542 - val_loss: 0.8032 - learning_rate: 0.0010

Epoch 6: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 6/50
227/227 ━━━━━━━━━━━━━━━━━━━━ 20s 88ms/step - accuracy: 0.5790 - 

In [28]:
import tensorflow as tf
import numpy as np
from sklearn.metrics import roc_auc_score

y_prob = model.predict(test_images)
y_prob = tf.nn.softmax(y_prob).numpy()

# Compute ROC AUC for each class
roc_auc = roc_auc_score(test_labels_encoded, y_prob, average='macro')

print("ROC AUC:", roc_auc)

10/57 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step

W0000 00:00:1713289153.405822      74 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


57/57 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step
ROC AUC: 0.999615352385477


W0000 00:00:1713289154.750851      77 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


In [29]:
# Save the model
model.save("my_cnn_model.h5")


In [30]:
import os
import numpy as np
directory = '/kaggle/working/test'

files = [file for file in os.listdir(directory) if file.endswith('.npy')]
len(files)

1279

In [31]:
mildDem = [i for i in files if i.startswith("MildDem")]
moderateDem = [i for i in files if "ModerateDem" in i]
nonDem = [i for i in files if "NonDem" in i]
veryMild = [i for i in files if "VeryMildDem" in i]
print(len(mildDem), len(moderateDem), len(nonDem), len(veryMild))

179 12 640 448


In [32]:
import pandas as pd
l = [[mildDem, 0], [moderateDem, 1], [nonDem, 2], [veryMild, 3]]
x = []
for i in l:
    for j in i[0]:
        path = os.path.join("/kaggle/working/test", j)
        x.append([i[1], path])

df = pd.DataFrame(x, columns=["Class", "Path"])
df["Class"].value_counts()


Class
2    640
3    448
0    179
1     12
Name: count, dtype: int64

In [33]:
images = []
for i in df["Path"]:
    images.append(np.load(i))
images = np.array(images)

In [34]:
labels = df["Class"]
labels = to_categorical(labels, num_classes=4)
# Verify the encoded labels
print(labels.shape)

(1279, 4)


In [35]:
l = []
for i in labels:
  for j in range(4):
    if i[j] == 1:
      l.append(j)


In [36]:
y_prob = model.predict(images)

# y_prob = tf.nn.softmax(y_prob).numpy()
# Get the class with the highest probability for each prediction
y_prob = np.argmax(y_prob, axis=1)  # Argmax gives index of max value
# for i in range(len(labels)):
#   print(l[i], y_prob[i])

40/40 ━━━━━━━━━━━━━━━━━━━━ 6s 155ms/step


W0000 00:00:1713289180.198886      74 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


In [37]:
from sklearn.metrics import classification_report

# Assuming you have predicted labels (predicted_classes) and true labels (test_labels_encoded)
report = classification_report(l, y_prob, output_dict=True)
for i in report:
  print(i, report[i])

0 {'precision': 0.44727272727272727, 'recall': 0.6871508379888268, 'f1-score': 0.5418502202643173, 'support': 179}
1 {'precision': 0.2222222222222222, 'recall': 0.5, 'f1-score': 0.30769230769230765, 'support': 12}
2 {'precision': 0.7339971550497866, 'recall': 0.80625, 'f1-score': 0.7684288905435591, 'support': 640}
3 {'precision': 0.7700729927007299, 'recall': 0.47098214285714285, 'f1-score': 0.5844875346260389, 'support': 448}
accuracy 0.6692728694292416
macro avg {'precision': 0.5433912743113665, 'recall': 0.6160957452114924, 'f1-score': 0.5506147382815557, 'support': 1279}
weighted avg {'precision': 0.7017039599767595, 'recall': 0.6692728694292416, 'f1-score': 0.6679659128850381, 'support': 1279}


In [38]:
model.evaluate(images, labels)

40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.7153 - loss: 1.9972


W0000 00:00:1713289188.161135      77 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update


[2.5136075019836426, 0.6692728400230408]